
import os
import glob 

cxx = ARGUMENTS.get('cxx', Environment()['CXX'])
cflags = ARGUMENTS.get('cflags', '-Wall -W')
release = int(ARGUMENTS.get('release', 1))
if release:
	debug = 0
	opt = '-O3'
else:
	debug = 1
	opt = '-O0'
debug = int(ARGUMENTS.get('debug', debug))
opt = ARGUMENTS.get('opt', opt)
cflags += ' ' + opt
if debug:
	cflags += ' -g -ggdb3'
	cppdef = ['DEBUG']
else:
	cppdef = ['NDEBUG']
caux = ARGUMENTS.get('aux', '')
cflags += ' ' + caux
cflagsoverride = ARGUMENTS.get('cfoverride', 0)
if cflagsoverride:
	cflags = cflagsoverride

env = Environment(
		  CXX = cxx, 
		  CCFLAGS = cflags, 
		  CPPPATH=['#/..'], 
		  CPPDEFINES=cppdef)

Export('env')
conf = SConscript('../../gott/configure/SConscript')
env = conf.Finish()

SConscript(dirs = ['x11'])

source_files = []
for root, dirs, _ in os.walk('.'):
	if '.svn' in dirs:
		dirs.remove('.svn')
	if 'test' in dirs:
		dirs.remove('test')
	source_files += glob.glob(root + '/*.cpp')

env.SharedLibrary('gottbase', source_files)


