import os
import glob

Import('env')
Import('rlib')

source_files = ['input.cpp','window.cpp','application.cpp', rlib + '.cpp']



#env.SharedLibrary('gottx11', source_files)
env.StaticLibrary('gottx11', source_files)


