import glob
Import('shrd')
Import('env')

my_env = env.Copy()
my_env.ParseConfig('pkg-config --libs sigc++-2.0')
my_env.ParseConfig('pkg-config --cflags sigc++-2.0')

my_shrd = shrd.Copy()
my_shrd.ParseConfig('pkg-config --libs sigc++-2.0')
my_shrd.ParseConfig('pkg-config --cflags sigc++-2.0')

my_shrd.SharedLibrary('notify_fs', ['watch.cpp', 'engine.cpp'])
my_shrd.SharedLibrary('notify_inotify', glob.glob('inotify/*.cpp'))
my_env.Program('test', 'test.cpp', LIBS = ['syswrap', 'string', 'events', 'notify_fs', 'notify_inotify'])
