import glob
Import('shrd')
Import('env')
shrd.SharedLibrary('notify_fs', ['watch.cpp', 'engine.cpp'])
shrd.SharedLibrary('notify_inotify', glob.glob('inotify/*.cpp'))
env.Program('test', 'test.cpp', LIBS = ['string', 'events', 'notify_fs', 'notify_inotify'])
