import string 

def filter_flag(flags,flag):
	nflags = []
	for f in flags:
		if f != flag:
			nflags	+= [f]
	return nflags

cppdef = Split(ARGUMENTS.get('def', ''))
cxx = ARGUMENTS.get('cxx', Environment()['CXX'])
cflags = Split(ARGUMENTS.get('cflags', ''))
release = int(ARGUMENTS.get('release', 1))
if release:
	debug = 0
	optimize = 'full'
	debug = -1
else:
	debug = 1
	optimize = 'none'

debug = int(ARGUMENTS.get('debug', debug))

if debug == 1:
	cppdef += ['DEBUG']
elif debug == -1:
	cppdef += ['NDEBUG']

optimize = ARGUMENTS.get('optimize', optimize)

rlib = ARGUMENTS.get('rlib', 'antigrain')

if rlib == 'antigrain':
	cppdef += ['USE_ANTIGRAIN']
elif rlib == 'cairo':
	cppdef += ['USE_CAIRO']
  



caux = ARGUMENTS.get('aux')
cflags += Split(caux)

cflagsoverride = ARGUMENTS.get('cfoverride', 0)
if cflagsoverride:
	cflags = cflagsoverride

cflags += ['-I../../']
env = Environment(
  CXX = cxx, 
  CCFLAGS = cflags, 
  CPPPATH=['#/..'], 
  LIBPATH=['x11/'],
  CPPDEFINES=cppdef)

Export('env')
Export('optimize')
Export('debug')
Export('rlib')

conf = SConscript('../../gott/configure/SConscript')
env = conf.Finish()

# Should this be inf configure/?
if rlib =='antigrain':
	print "Using antigrain..."
	env.ParseConfig('pkg-config --cflags  libagg')
	env.ParseConfig('pkg-config --libs libagg')
	cflags = filter_flag(env['CCFLAGS'],'-Werror')
	env.Replace(CCFLAGS = cflags)
else:
	print "Using cairo..."	
	env.ParseConfig('pkg-config --cflags cairo')
	env.ParseConfig('pkg-config --libs cairo')


shrd = env.Copy()
shrd.Append(CPPDEFINES = 'BUILDING_DLL')

Export('shrd')

SConscript(dirs = ['x11'])

source_files = ['input.cpp', 'utility.cpp', 'widget_events.cpp']

#env.SharedLibrary('gottbase', source_files)
env.StaticLibrary('gottbase', source_files)

x11_example_files= ['test_x11.cpp']
our_libs=['gottx11', 'gottbase' ,'X11', 'boost_signals',  'z' ]

env.Append(LIBS=our_libs)
env.Append(LIBPATH=['.', 'x11/','/usr/X11R6/lib'])
env.Program('test_x11', x11_example_files )

