Import('env')

env.SharedLibrary('select_loop', 'select_loop.cpp', LIBS = [], SHLIBSUFFIX='.plugin')
if env['SYS_EPOLL']:
	env.SharedLibrary('epoll_loop', 'epoll_loop.cpp', LIBS = [], SHLIBSUFFIX='.plugin')
if env['SYS_KQUEUE']:
	env.SharedLibrary('kqueue_loop', 'kqueue_loop.cpp', LIBS = [], SHLIBSUFFIX='.plugin')
env.SharedLibrary('message_queue_loop', 'message_queue_loop.cpp', LIBS = [], SHLIBSUFFIX = '.plugin')
