import os
import glob

Import('env')


env.Append(CCFLAGS=['-I./'])
designer_files= ['designer.cpp', 'simple_handle.cpp', 'handle.cpp', 'vector_obj.cpp', 'rounded_rect.cpp']
env.Program('designer', designer_files, LIBPATH=['../', '../x11'] )


