import glob

Import('shrd')
Import('env')

conf = Configure(shrd.Copy())
conf.CheckLib('boost_thread', language = 'c++')
conf.CheckLib('boost_date_time', language = 'c++')
my_shrd = conf.Finish()
my_shrd.ParseConfig('pkg-config --libs sigc++-2.0')
my_shrd.ParseConfig('pkg-config --cflags sigc++-2.0')

my_env = env.Copy()
my_env.ParseConfig('pkg-config --libs sigc++-2.0')
my_env.ParseConfig('pkg-config --cflags sigc++-2.0')

libobj = glob.glob('*.cpp')
libobj.remove('auto_loop_test.cpp')
libobj.remove('mq_test.cpp')
my_shrd.SharedLibrary('events', libobj)
my_env.Program('auto_loop', 'auto_loop_test.cpp', LIBS=['string','events'])
my_env.Program('mq', 'mq_test.cpp', LIBS=['string','events'])
