import glob

Import('shrd')
Import('env')

libobj = glob.glob('*.cpp')
libobj.remove('auto_loop_test.cpp')
libobj.remove('mq_test.cpp')
shrd.SharedLibrary('events', libobj, LIBS='boost_date_time')
env.Program('auto_loop', 'auto_loop_test.cpp', LIBS=['ntl','string','events'])
env.Program('mq', 'mq_test.cpp', LIBS=['boost_thread','ntl','string','events'])
