def CheckCompilerVisibility(context):
	context.Message('Checking if compiler supports visibility attributes...')
	lastCPPDEF = context.env['CPPDEFINES'][:]
	lastCCFLAGS = context.env['CCFLAGS']
	
	context.env.Append(CPPDEFINES = 'HAVE_VISIBILITY')
	context.env.Append(CCFLAGS='-fvisibility=hidden')

	result = context.TryCompile('int global __attribute((visibility("default")));', '.c')
	if not result:
		context.env.Replace(CCFLAGS = lastCCFLAGS)
		context.env.Replace(CPPDEFINES = lastCPPDEF)
	context.Result(result)
	return result

print 'Configuration...'
Import('env')
conf = Configure(env, custom_tests = {'CheckCompilerVisibility': CheckCompilerVisibility})
conf.CheckCompilerVisibility()

Return('conf')
print 'Finished configuration'
